import { createHash, randomUUID } from "node:crypto";
import type { Attachment } from "../shared/attachments.ts";
import type { Provider } from "../shared/types.ts";
import { validateEndpoint } from "./security.ts";

const imageKinds = new Set(["png", "jpg", "jpeg", "webp"]);

function dataUrlToBlob(dataUrl: string) {
  const match = /^data:([^;,]+);base64,(.+)$/i.exec(dataUrl);
  if (!match) throw new Error("Image attachment must be a data URL.");
  const buffer = Buffer.from(match[2], "base64");
  return {
    mediaType: match[1],
    buffer,
    blob: new Blob([buffer], { type: match[1] }),
  };
}

function attachmentFromB64(
  b64: string,
  input: {
    runId: string;
    role: string;
    prompt: string;
    provider: Provider;
    model: string;
  },
): Attachment {
  const buffer = Buffer.from(b64, "base64");
  const sha256 = createHash("sha256").update(buffer).digest("hex");
  const name = `generated-${input.role}-${sha256.slice(0, 10)}.png`;
  return {
    id: randomUUID(),
    name,
    kind: "png",
    size: buffer.length,
    sha256,
    text: "",
    mediaType: "image/png",
    dataUrl: `data:image/png;base64,${b64}`,
    warnings: [
      `Generated by ${input.provider.name} (${input.model}) for run ${input.runId}.`,
      `Prompt: ${input.prompt.slice(0, 500)}`,
    ],
  };
}

function selectImageProvider(
  providers: Provider[],
  providerId?: string,
): Provider {
  const provider = providerId
    ? providers.find((p) => p.id === providerId)
    : providers.find((p) => p.kind === "openai" && p.transport === "direct");
  if (!provider)
    throw new Error(
      "No selected direct OpenAI provider is available for image generation/editing.",
    );
  if (provider.kind !== "openai" || provider.transport !== "direct")
    throw new Error(
      `${provider.name} is not supported for built-in image generation/editing yet. Use a direct OpenAI connection.`,
    );
  if (!provider.apiKey)
    throw new Error(`${provider.name} needs an API key for image tools.`);
  return provider;
}

async function imageResponse(response: Response, provider: Provider) {
  const payload = await response.json().catch(() => ({}));
  if (!response.ok)
    throw new Error(
      `${provider.name} image request failed: ${payload?.error?.message || response.status}`,
    );
  const b64 =
    payload?.data?.[0]?.b64_json ||
    payload?.b64_json ||
    payload?.output?.find?.((item: any) => item?.b64_json)?.b64_json;
  if (!b64)
    throw new Error(
      `${provider.name} did not return b64_json image data. Check the image model and response format support.`,
    );
  return b64 as string;
}

export async function generateImage(
  providers: Provider[],
  input: {
    runId: string;
    providerId?: string;
    model?: string;
    prompt: string;
    size?: string;
    signal: AbortSignal;
  },
) {
  const provider = selectImageProvider(providers, input.providerId);
  const model = input.model || "gpt-image-1";
  const base = validateEndpoint(provider.baseUrl);
  const body: Record<string, string> = {
    model,
    prompt: input.prompt,
    size: input.size || "1024x1024",
  };
  // GPT image models return b64_json by default and reject response_format.
  if (!model.startsWith("gpt-image-")) body.response_format = "b64_json";
  const response = await fetch(base + "/images/generations", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${provider.apiKey}`,
    },
    body: JSON.stringify(body),
    signal: input.signal,
    redirect: "error",
  });
  return attachmentFromB64(await imageResponse(response, provider), {
    runId: input.runId,
    role: "image",
    prompt: input.prompt,
    provider,
    model,
  });
}

export async function editImage(
  providers: Provider[],
  attachments: Attachment[],
  input: {
    runId: string;
    providerId?: string;
    model?: string;
    prompt: string;
    sourceAttachmentName?: string;
    size?: string;
    signal: AbortSignal;
  },
) {
  const provider = selectImageProvider(providers, input.providerId);
  const model = input.model || "gpt-image-1";
  const source =
    (input.sourceAttachmentName
      ? attachments.find((a) => a.name === input.sourceAttachmentName)
      : [...attachments]
          .reverse()
          .find((a) => a.dataUrl && imageKinds.has(a.kind))) || undefined;
  if (!source?.dataUrl)
    throw new Error(
      "No image attachment is available to edit. Attach a .png, .jpg, .jpeg or .webp image.",
    );
  const image = dataUrlToBlob(source.dataUrl);
  const form = new FormData();
  form.append("model", model);
  form.append("prompt", input.prompt);
  form.append("size", input.size || "1024x1024");
  // GPT image models return b64_json by default and reject response_format.
  if (!model.startsWith("gpt-image-")) form.append("response_format", "b64_json");
  form.append("image", image.blob, source.name);
  const base = validateEndpoint(provider.baseUrl);
  const response = await fetch(base + "/images/edits", {
    method: "POST",
    headers: { Authorization: `Bearer ${provider.apiKey}` },
    body: form,
    signal: input.signal,
    redirect: "error",
  });
  return attachmentFromB64(await imageResponse(response, provider), {
    runId: input.runId,
    role: "image-edit",
    prompt: input.prompt,
    provider,
    model,
  });
}
